// lib/pages/SavedAnalyticsPage.dart

/*
Currently the Chat Page creates saved reports in memory (RAM).
Later connect to a real database (Supabase/Neon/AWS S3/etc...) to store the saved reports
for longer.
*/
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:dashboard_flutter/ReusableConstants/constants.dart';
import 'package:dashboard_flutter/services/report_service.dart';

class SavedAnalyticsPage extends StatelessWidget {
  const SavedAnalyticsPage({super.key});

  @override
  Widget build(BuildContext context) {
    final reportService = ReportService();

    return Padding(
      padding: const EdgeInsets.all(40),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            "Saved Reports",
            style: TextStyle(
              fontSize: 32,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
          const SizedBox(height: 8),
          const Text(
            "Analytics generated by AI during your sessions.",
            style: TextStyle(color: kTextGrey),
          ),
          const SizedBox(height: 40),

          Expanded(
            child: ValueListenableBuilder<List<Report>>(
              valueListenable: reportService.reportsNotifier,
              builder: (context, reports, child) {
                // 1. Empty State
                if (reports.isEmpty) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(
                          Icons.folder_open_rounded,
                          size: 64,
                          color: Colors.white.withOpacity(0.2),
                        ),
                        const SizedBox(height: 16),
                        Text(
                          "No reports generated yet.",
                          style: TextStyle(
                            color: Colors.white.withOpacity(0.4),
                          ),
                        ),
                        const SizedBox(height: 8),
                        OutlinedButton(
                          onPressed: () {
                            // Helper to test: Add a dummy file immediately
                            ReportService().addReport(
                              "Test_Analysis",
                              "ID,Name,Value\n1,Test,100",
                              "csv",
                            );
                          },
                          style: OutlinedButton.styleFrom(
                            foregroundColor: kNeonGreen,
                            side: const BorderSide(color: kNeonGreen),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(24),
                            ),
                          ),
                          child: const Text("Generate Test Report"),
                        ),
                      ],
                    ),
                  );
                }

                // 2. List of Real Reports
                return ListView.builder(
                  itemCount: reports.length,
                  itemBuilder: (context, index) {
                    return _buildReportItem(reports[index]);
                  },
                );
              },
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildReportItem(Report report) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: kSurfaceBlack,
        border: Border.all(color: Colors.white10),
        // UPDATED: Smooth rounded corners
        borderRadius: BorderRadius.circular(24),
      ),
      child: Row(
        children: [
          // UPDATED: Icon with circular background
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: kNeonGreen.withOpacity(0.1),
              shape: BoxShape.circle,
            ),
            child: Icon(
              report.type.toLowerCase() == 'csv'
                  ? Icons.table_chart_rounded
                  : Icons.description_rounded,
              color: kNeonGreen,
              size: 24,
            ),
          ),
          const SizedBox(width: 24),

          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  report.name,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  "${report.type.toUpperCase()} • ${report.size}",
                  style: const TextStyle(color: kTextGrey, fontSize: 12),
                ),
              ],
            ),
          ),

          Text(
            DateFormat('MMM d, h:mm a').format(report.date),
            style: const TextStyle(color: kTextGrey, fontSize: 14),
          ),
          const SizedBox(width: 24),

          // Download Button
          PopupMenuButton<String>(
            icon: const Icon(Icons.download_rounded, color: Colors.white),
            color: kSurfaceBlack,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
              side: const BorderSide(color: Colors.white10),
            ),
            onSelected: (value) {
              if (value == 'txt') ReportService().downloadAsTxt(report);
              if (value == 'excel') ReportService().downloadAsExcel(report);
            },
            itemBuilder: (context) => [
              _buildMenuItem('txt', Icons.text_snippet, "Text File"),
              _buildMenuItem('excel', Icons.table_chart, "Excel Sheet"),
            ],
          ),
        ],
      ),
    );
  }

  PopupMenuItem<String> _buildMenuItem(
    String value,
    IconData icon,
    String text,
  ) {
    return PopupMenuItem(
      value: value,
      child: Row(
        children: [
          Icon(icon, size: 18, color: kNeonGreen),
          const SizedBox(width: 12),
          Text(text, style: const TextStyle(color: Colors.white)),
        ],
      ),
    );
  }
}
