// lib/pages/SavedAnalyticsPage.dart

/*
Currently the Chat Page creates saved reports in memory (RAM).
Later connect to a real database (Supabase/Neon/AWS S3/etc...) to store the saved reports
for longer.
*/
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:dashboard_flutter/ReusableConstants/constants.dart';
import 'package:dashboard_flutter/services/report_service.dart';
import 'package:dashboard_flutter/services/downloader/downloader.dart';
import 'package:excel/excel.dart' hide Border;

class SavedAnalyticsPage extends StatelessWidget {
  const SavedAnalyticsPage({super.key});

  // --- 1.Generate Real Excel Bytes ---
  List<int>? _generateExcelBytes(String csvContent) {
    try {
      var excel = Excel.createExcel();
      Sheet sheetObject = excel['Sheet1'];

      // Parse the CSV-like string content
      List<String> lines = const LineSplitter().convert(csvContent);

      for (var line in lines) {
        List<String> cells = line.split(',');
        sheetObject.appendRow(
          cells.map((e) => TextCellValue(e.trim())).toList(),
        );
      }

      return excel.encode();
    } catch (e) {
      debugPrint("Excel generation error: $e");
      return null;
    }
  }

  // --- 2. DOWNLOAD HANDLER ---
  Future<void> _handleDownload(
    BuildContext context,
    Report report,
    String type,
  ) async {
    final String data = report.content ?? "No content available";
    List<int>? bytes;
    String fileName = report.name;
    String mimeType = 'text/plain';

    // LOGIC: Check Type and Generate Bytes
    if (type == 'excel') {
      // A. Generate Real Excel (.xlsx)
      bytes = _generateExcelBytes(data);
      if (bytes == null) {
        _showSnack(context, "Failed to generate Excel file", isError: true);
        return;
      }
      fileName = "$fileName.xlsx";
      mimeType =
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    } else {
      // B. Generate Text (.txt)
      bytes = utf8.encode(data);
      fileName = "$fileName.txt";
      mimeType = 'text/plain';
    }

    // C. Call the Downloader
    await downloadFile(bytes, fileName, mimeType);

    // D. Feedback
    if (context.mounted) {
      _showSnack(context, "Saved $fileName to Downloads");
    }
  }

  void _showSnack(BuildContext context, String msg, {bool isError = false}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(msg),
        backgroundColor: isError ? Colors.redAccent : Colors.green,
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final reportService = ReportService();
    // Responsive padding to match HomePage
    final isMobile = Responsive.isMobile(context);
    final padding = isMobile ? 24.0 : 40.0;

    return Padding(
      padding: EdgeInsets.all(padding),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            "Saved Reports",
            style: TextStyle(
              fontSize: isMobile ? 24 : 32,
              fontWeight: FontWeight.bold,
              color: kTextWhite,
            ),
          ),
          const SizedBox(height: 8),
          const Text(
            "Analytics generated by AI during your sessions.",
            style: TextStyle(color: kTextGrey),
          ),
          const SizedBox(height: 40),

          Expanded(
            child: ValueListenableBuilder<List<Report>>(
              valueListenable: reportService.reportsNotifier,
              builder: (context, reports, child) {
                // 1. Empty State
                if (reports.isEmpty) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(
                          Icons.folder_open_rounded,
                          size: 64,
                          color: kBankSurfaceLight, // Theme Update
                        ),
                        const SizedBox(height: 16),
                        const Text(
                          "No reports generated yet.",
                          style: TextStyle(color: kTextGrey),
                        ),
                        const SizedBox(height: 16),
                        OutlinedButton(
                          onPressed: () {
                            // Helper to test: Add a dummy file immediately
                            ReportService().addReport(
                              "Test_Analysis",
                              "ID,Name,Value\n1,Test,100",
                              "csv",
                            );
                          },
                          style: OutlinedButton.styleFrom(
                            foregroundColor: kBankPrimary, // Theme Update
                            side: const BorderSide(color: kBankPrimary),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                            padding: const EdgeInsets.symmetric(
                              horizontal: 24,
                              vertical: 16,
                            ),
                          ),
                          child: const Text("Generate Test Report"),
                        ),
                      ],
                    ),
                  );
                }

                // 2. List of Real Reports
                return ListView.separated(
                  itemCount: reports.length,
                  separatorBuilder: (_, __) => const SizedBox(height: 12),
                  itemBuilder: (context, index) {
                    return _buildReportItem(context, reports[index]);
                  },
                );
              },
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildReportItem(BuildContext context, Report report) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: kBankSurface, // Theme Update
        border: Border.all(color: kBorderColor), // Theme Update
        borderRadius: BorderRadius.circular(16), // Consistent Radius
      ),
      child: Row(
        children: [
          // UPDATED: Icon with circular background
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: kBankPrimary.withOpacity(0.1), // Theme Update
              shape: BoxShape.circle,
            ),
            child: Icon(
              report.type.toLowerCase() == 'csv'
                  ? Icons.table_chart_rounded
                  : Icons.description_rounded,
              color: kBankPrimary, // Theme Update
              size: 24,
            ),
          ),
          const SizedBox(width: 20),

          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  report.name,
                  style: const TextStyle(
                    color: kTextWhite,
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  "${report.type.toUpperCase()} • ${report.size}",
                  style: const TextStyle(color: kTextGrey, fontSize: 12),
                ),
              ],
            ),
          ),

          // Date (Hidden on very small screens if needed, but kept here)
          Text(
            DateFormat('MMM d, h:mm a').format(report.date),
            style: const TextStyle(color: kTextGrey, fontSize: 13),
          ),
          const SizedBox(width: 16),

          // Download Button
          PopupMenuButton<String>(
            icon: const Icon(Icons.download_rounded, color: kTextGrey),
            color: kBankSurface,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
              side: const BorderSide(color: kBorderColor),
            ),
            onSelected: (value) => _handleDownload(context, report, value),
            itemBuilder: (context) => [
              _buildMenuItem('txt', Icons.text_snippet_rounded, "Text File"),
              _buildMenuItem('excel', Icons.grid_on_rounded, "Excel / CSV"),
            ],
          ),
        ],
      ),
    );
  }

  PopupMenuItem<String> _buildMenuItem(
    String value,
    IconData icon,
    String text,
  ) {
    return PopupMenuItem(
      value: value,
      child: Row(
        children: [
          Icon(icon, size: 18, color: kBankPrimary), // Theme Update
          const SizedBox(width: 12),
          Text(text, style: const TextStyle(color: kTextWhite)),
        ],
      ),
    );
  }
}
