// lib/pages/SavedAnalyticsPage.dart

/*
Currently the Chat Page creates saved reports in memory (RAM).
Later connect to a real database (Supabase/Neon/AWS S3/etc...) to store the saved reports
for longer.
*/
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:dashboard_flutter/ReusableConstants/constants.dart';
import 'package:dashboard_flutter/services/report_service.dart';

class SavedAnalyticsPage extends StatelessWidget {
  const SavedAnalyticsPage({super.key});

  @override
  Widget build(BuildContext context) {
    final reportService = ReportService();
    // Responsive padding to match HomePage
    final isMobile = Responsive.isMobile(context);
    final padding = isMobile ? 24.0 : 40.0;

    return Padding(
      padding: EdgeInsets.all(padding),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            "Saved Reports",
            style: TextStyle(
              fontSize: isMobile ? 24 : 32,
              fontWeight: FontWeight.bold,
              color: kTextWhite,
            ),
          ),
          const SizedBox(height: 8),
          const Text(
            "Analytics generated by AI during your sessions.",
            style: TextStyle(color: kTextGrey),
          ),
          const SizedBox(height: 40),

          Expanded(
            child: ValueListenableBuilder<List<Report>>(
              valueListenable: reportService.reportsNotifier,
              builder: (context, reports, child) {
                // 1. Empty State
                if (reports.isEmpty) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(
                          Icons.folder_open_rounded,
                          size: 64,
                          color: kBankSurfaceLight, // Theme Update
                        ),
                        const SizedBox(height: 16),
                        const Text(
                          "No reports generated yet.",
                          style: TextStyle(
                            color: kTextGrey,
                          ),
                        ),
                        const SizedBox(height: 16),
                        OutlinedButton(
                          onPressed: () {
                            // Helper to test: Add a dummy file immediately
                            ReportService().addReport(
                              "Test_Analysis",
                              "ID,Name,Value\n1,Test,100",
                              "csv",
                            );
                          },
                          style: OutlinedButton.styleFrom(
                            foregroundColor: kBankPrimary, // Theme Update
                            side: const BorderSide(color: kBankPrimary),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
                          ),
                          child: const Text("Generate Test Report"),
                        ),
                      ],
                    ),
                  );
                }

                // 2. List of Real Reports
                return ListView.separated(
                  itemCount: reports.length,
                  separatorBuilder: (_, __) => const SizedBox(height: 12),
                  itemBuilder: (context, index) {
                    return _buildReportItem(reports[index]);
                  },
                );
              },
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildReportItem(Report report) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: kBankSurface, // Theme Update
        border: Border.all(color: kBorderColor), // Theme Update
        borderRadius: BorderRadius.circular(16), // Consistent Radius
      ),
      child: Row(
        children: [
          // UPDATED: Icon with circular background
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: kBankPrimary.withOpacity(0.1), // Theme Update
              shape: BoxShape.circle,
            ),
            child: Icon(
              report.type.toLowerCase() == 'csv'
                  ? Icons.table_chart_rounded
                  : Icons.description_rounded,
              color: kBankPrimary, // Theme Update
              size: 24,
            ),
          ),
          const SizedBox(width: 20),

          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  report.name,
                  style: const TextStyle(
                    color: kTextWhite,
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  "${report.type.toUpperCase()} • ${report.size}",
                  style: const TextStyle(color: kTextGrey, fontSize: 12),
                ),
              ],
            ),
          ),

          // Date (Hidden on very small screens if needed, but kept here)
          Text(
            DateFormat('MMM d, h:mm a').format(report.date),
            style: const TextStyle(color: kTextGrey, fontSize: 13),
          ),
          const SizedBox(width: 16),

          // Download Button
          PopupMenuButton<String>(
            icon: const Icon(Icons.download_rounded, color: kTextGrey),
            color: kBankSurface,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
              side: const BorderSide(color: kBorderColor),
            ),
            onSelected: (value) {
              if (value == 'txt') ReportService().downloadAsTxt(report);
              if (value == 'excel') ReportService().downloadAsExcel(report);
            },
            itemBuilder: (context) => [
              _buildMenuItem('txt', Icons.text_snippet_rounded, "Text File"),
              _buildMenuItem('excel', Icons.grid_on_rounded, "Excel Sheet"),
            ],
          ),
        ],
      ),
    );
  }

  PopupMenuItem<String> _buildMenuItem(
    String value,
    IconData icon,
    String text,
  ) {
    return PopupMenuItem(
      value: value,
      child: Row(
        children: [
          Icon(icon, size: 18, color: kBankPrimary), // Theme Update
          const SizedBox(width: 12),
          Text(text, style: const TextStyle(color: kTextWhite)),
        ],
      ),
    );
  }
}